apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: nginx-vs
    version: v1
  name: nginx-vs
  namespace: default
spec:
  hosts:
  - nginx
  http:
  - route:
    - destination:
        host: nginx
        port:
          number: 80
        subset: v1
      weight: 100
