apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    version: v1
  name: nginx
  namespace: default
spec:
  ports: {{ index .Values "nginxSVC" "ports" | toYaml | trim | nindent 4 }}
  selector:
    app: nginx
  type: {{ index .Values "nginxSVC" "type" }}
