apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app: helloworld-gtw
    version: v1
  name: helloworld-gtw
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
