apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: helloworld-vs
    version: v1
  name: helloworld-vs
  namespace: default
spec:
  gateways:
  - helloworld-gtw
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: helloworld
        port:
          number: 3000
        subset: v1
      weight: 100
