{{- if .Values.rbac.create  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "secret-reader.labels" . | nindent 4 }}
  name: {{ template "secret-reader.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list

{{- end }}
