{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metdata:
  labels: {{- include "read-pods.labels" . | nindent 4 }}
  name: {{ template "read-pods.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "pod-reader.fullname" . }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: jane
  namespace: null

{{- end }}
