{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: {{- include "pod-reader.labels" . | nindent 4 }}
  name: {{ template "pod-reader.fullname" . }}
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list

{{- end }}
